version: '3'
services:

    php:
        image: atillay/craftcms3-php
        volumes:
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
            - .:/var/www

    nginx:
        image: atillay/craftcms3-nginx
        ports:
            - ${CRAFT_PORT}:80
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./log:/var/log/nginx
            - ./web:/var/www/web

    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=StrongPassword
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - ${PMA_PORT}:80
        environment:
            - PMA_HOST=${DB_SERVER}

    maildev:
        image: djfarrelly/maildev
        ports:
            - ${MAILDEV_PORT}:80
